name: Build and Publish on Netlify

on:
  push:
    branches: [prod]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repo Code
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Add Issues from Comments
        uses: "alstr/todo-to-issue-action@v5"
        with:
          AUTO_ASSIGN: true
          CLOSE_ISSUES: true

      - name: Install Node Packages
        run: npm install

      - name: Deploy to Netlify
        id: build_site
        uses: netlify/actions/cli@master
        with:
          args: deploy --build --prod --message "Probably a new post"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

